planning/constraints.md

constraints.md file added

---

planning/communication-plan.md

PR - Communication plan created

---

.cspell.json
planning/communication-plan.md

uploading Cristobal's availability

---

planning/communication-plan.md

Communication

---

.cspell.json
planning/development-strategy.md

Development strategy.md

---

index.html
pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html
planning/communication-plan.md
styles/index.css

PR Landing page

---

index.html
styles/index.css

PR Landingpage

---

README.md
planning/backlog.md

PR - Backlog

---

README.md

README.md-collaboration update

---

.cspell.json
index.html
package.json
planning/constraints.md
styles/index.css

user persona added to landing page

---

index.html
styles/index.css

landingpage recoverd

---

pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html
styles/index.css

redesigning the form

---

index.html

PR landing page cosmetics and spellings

---

.cspell.json
pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html
styles/index.css

adding map to the contact section

---

styles/index.css

padding fixed

---

pages/coach.html
pages/sponsor.html
pages/student.html

fixing the padding of the form

---

pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html
styles/index.css

adding a title to the map

---

index.html
pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html

Home page edit

---

index.html
styles/index.css

PR newsletter added to homepage

---

pages/student.html
styles/index.css

PR added description-Student

---

.cspell.json
.stylelintrc.json
package-lock.json
package.json
styles/index.css

image in header darkened

---

pages/alumni.html
pages/coach.html
pages/sponsor.html

Pages update

---

pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html

updating the relative path for the css sheet

---

pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html

changing relative path

---

pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html

switching the path link

---

pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html

adding two dots to the link path

---

pages/alumni.html

fixing links in the navbar

---

index.html

offcanvas bootstrap creation

---

index.html
package-lock.json
package.json
pages/coach.html
styles/index.css

Coach image

---

.cspell.json
index.html
pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html
styles/index.css

bg img in header fixed

---

index.html
pages/alumni.html
pages/coach.html
pages/sponsor.html
pages/student.html
styles/index.css

newsletter copied to all pages

---

pages/alumni.html

alumni-update

---

pages/coach.html

image link fixed in coach page
